### ISSUE TITLE
Add Example Apps

### ISSUE THREAD

**Issue by oliver-gomes** [oliver-gomes/flutter-guide#2]
Please feel free to add some link of Flutter example apps to the Readme under Example Apps section. 

Happy Hacking 👨‍💻!

**Comment by DilkiSasikala** [comment]
I would like to attempt this one...I'll do the pull request after 1st of October.

**Comment by oliver-gomes** [comment]
Sure, would love to have your contributions. Others already started making PR so it's going to be good

**Comment by DilkiSasikala** [comment]
I'll do the PR after 1st of October...

**Comment by StrangeNoob** [comment]
is this still open ? I would also like to work on it !!

**Comment by oliver-gomes** [comment]
@StrangeNoob Yeah of course! It's Hacktoberfest so feel free to complete your challenge and get free swag 😄

**Comment by sivaram16** [comment]
I would like to work on this!
