### ISSUE TITLE
Add Learning Resource

### ISSUE THREAD

**Issue by oliver-gomes** [oliver-gomes/flutter-guide#3]
Please add any learning resources you find it to be helpful. Try adding the icons too 😊

Happy Hacking!

**Comment by DilkiSasikala** [comment]
I would like to attempt this one.

**Comment by oliver-gomes** [comment]
@DilkiSasikala Sure, you are most welcome! 😄

**Comment by hkp27299** [comment]
I  will help you in this add some basic app with preview if you like ?

**Comment by oliver-gomes** [comment]
@hkp27299 Yeah, sure! 😀

**Comment by phuocding** [comment]
I bookmark many resources online. Perhaps there are both tutorials and learning blog. can I add them into where now?

**Comment by oliver-gomes** [comment]
@phuocding There's Recommended Learning Resources Section, add those there. Thanks!

**Comment by phuocding** [comment]
@oliver-gomes check my PR out, enjoy! Many thanks :))

**Comment by sivaram16** [comment]
I would like to work on this!
