### ISSUE TITLE
Add more Widgets

### ISSUE THREAD

**Issue by oliver-gomes** [oliver-gomes/flutter-guide#4]
Please add more Widgets. I know there are many brand new ones.
Happy Hacking!

**Comment by vincentsong** [comment]
do you have a list of widgets to add?  I know there is a repo called 'Awesome Flutter' which has some good information.

**Comment by oliver-gomes** [comment]
@vincentsong I am aware of "Awesome Flutter" and the aim of this guide is to focus more on tutorial side. Also, it's open for Hacktoberfest participation

**Comment by sivaram16** [comment]
I would like to work on this!
